### ISSUE TITLE
Aliases are ignored + raw statements ignored

### ISSUE THREAD

**Issue by sameerpanjwani** [Big-Shark/sql-to-builder#7]
Example: 

`$builder = new \BigShark\SQLToBuilder\BuilderClass('SELECT phs.http_status_code,wp.page_id,CONCAT(wd.website_url,wp.page_url) as web_url FROM seoi_page_http_status phs LEFT JOIN seoi_website_pages wp ON  phs.redirected_page_id=wp.page_id LEFT JOIN seoi_website_details wd ON wp.website_id=wd.website_id WHERE phs.page_id="4323" ORDER BY phs.http_status_id DESC LIMIT 1');`

results in:

`DB::select('phs.http_status_code', 'wp.page_id')->table('seoi_page_http_status')->leftJoin('seoi_website_pages', 'phs.redirected_page_id', '=', 'wp.page_id')->leftJoin('seoi_website_details', 'wp.website_id', '=', 'wd.website_id')->where('phs.page_id', '=', '"4323"')->orderBy('phs.http_status_id', 'DESC')->take(1)->get()`

1) The table aliases are ignored

2) The raw component "CONCAT" is ignored

3) Ideally "select" should come just before "get()", putting select first throws a Laravel error

**Comment by Big-Shark** [comment]
Done, thx for you issue

**Comment by sameerpanjwani** [comment]
2) The raw component seems to be fine

Issues 1 & 3 still remain

1) The table alias is only coming for the first table and not coming for any of the joined tables

2) The output is still DB::select instead of DB::table ..when trying to execute query with DB::select, Laravel throws an error

**Comment by Big-Shark** [comment]
Check again please

**Comment by sameerpanjwani** [comment]
The output issues are corrected BUT for some reason the arrangement order of the joins is getting messed up which results in the query failing:

`DB::table('seoi_page_http_status AS phs')->orderBy('phs.http_status_id', 'DESC')->take(1)->where('phs.page_id', '=', '"4323"')->leftJoin('seoi_website_details AS wd', 'wp.website_id', '=', 'wd.website_id')->leftJoin('seoi_website_pages AS wp', 'phs.redirected_page_id', '=', 'wp.page_id')->select('phs.http_status_code', 'wp.page_id', DB::raw('CONCAT(wd.website_url, wp.page_url) AS web_url'))->get()`

Above is the output I get, which doesn't work when I try to run the query

It works if I correct the order of the joins as was intended in the original query. The second left join should be the first one, then only works. So not sure what you changed but everything is fine except the way the query order is built.

**Comment by Big-Shark** [comment]
Fixed, this is stupid php5 bug https://3v4l.org/VHMLJ

**Comment by sameerpanjwani** [comment]
Yes works perfectly now, thanks!

**Comment by Big-Shark** [comment]
You are welcome )
